[package]
name = "cli"
version = "0.0.0"
edition = "2018"

[dependencies]
hash_engine = { path = "../.." }

argh = "0.1.4"
async-trait = "0.1.48"
lazy_static = "1.4.0"
log = "0.4.11"
pretty_env_logger = "0.4.0"
rand = "0.8.3"
rand_distr = "0.4.2"
serde = { version = "1.0.111", features = ["derive"] }
serde_json = "1.0.59"
thiserror = "1.0.21"
tokio = { version = "1.5.0", features = ["macros", "rt-multi-thread", "sync", "process", "io-util", "net", "rt", "fs"] }
