frontend:
  - packages/hash/frontend/*
  - packages/hash/frontend/.*
  - packages/hash/frontend/**/*
  - packages/hash/frontend/**/.*

backend:
  - packages/hash/backend/*
  - packages/hash/backend/.*
  - packages/hash/backend/**/*
  - packages/hash/backend/**/.*

blocks:
  - packages/hash/blocks/*
  - packages/hash/blocks/.*
  - packages/hash/blocks/**/*
  - packages/hash/blocks/**/.*

integration:
  - packages/hash/integration/*
  - packages/hash/integration/.*
  - packages/hash/integration/**/*
  - packages/hash/integration/**/.*

docker:
  - packages/hash/docker/*
  - packages/hash/docker/.*
  - packages/hash/docker/**/*
  - packages/hash/docker/**/.*

realtime:
  - packages/hash/realtime/*
  - packages/hash/realtime/.*
  - packages/hash/realtime/**/*
  - packages/hash/realtime/**/.*

search-loader:
  - packages/hash/search-loader/*
  - packages/hash/search-loader/.*
  - packages/hash/search-loader/**/*
  - packages/hash/search-loader/**/.*
