version: "3.9"
services:
    hash-dev-pg:
        build:
            context: ../../../
            dockerfile: packages/hash/docker/postgres/Dockerfile
        ports:
            - 5432:5432
        environment:
            - PGDATA=/pgdata
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - hash-dev-pg:/pgdata
    hash-dev-api:
        build:
            context: ../../../
            dockerfile: packages/hash/docker/api/dev/Dockerfile
        depends_on:
            - hash-dev-pg
        ports:
            - 5001:5001
        environment:
            - HASH_PG_HOST=hash-dev-pg
            - HASH_PG_USER=postgres
            - HASH_PG_PORT=5432
            - HASH_PG_DATABASE=postgres
            - HASH_PG_PASSWORD=postgres
            - SESSION_SECRET=secret
            - FRONTEND_DOMAIN=localhost:3000
            - AWS_REGION=${AWS_REGION}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        # Wait until the database is running before starting the API
        command: ["wait-for-it", "-h", "hash-dev-pg", "-p", "5432", "-s", "-t", "30", "--", "./start.sh"]
        volumes:
            - ../backend/src:/app/src
        stop_signal: SIGINT
volumes:
    # Make sure you have created this volume: docker volume create hash-dev-pg
    hash-dev-pg:
        external: true
