version: "3.9"
services:
    hash-dev-pg:
        build:
            context: ../../../
            dockerfile: packages/hash/docker/postgres/Dockerfile
        ports:
            - 5432:5432
        environment:
            - PGDATA=/pgdata
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - hash-dev-pg:/pgdata
            - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
        command: ["-c", "config_file=/etc/postgresql/postgresql.conf"]
    hash-dev-redis:
        image: redis:6.2
        ports:
            - 6379:6379
    hash-dev-api:
        build:
            context: ../../../
            dockerfile: packages/hash/docker/api/dev/Dockerfile
        depends_on:
            - hash-dev-pg
            - hash-dev-redis
        ports:
            - 5001:5001
        environment:
            - HASH_PG_HOST=hash-dev-pg
            - HASH_PG_USER=postgres
            - HASH_PG_PORT=5432
            - HASH_PG_DATABASE=${HASH_PG_DATABASE:-postgres}
            - HASH_PG_PASSWORD=postgres
            - HASH_REDIS_HOST=hash-dev-redis
            - HASH_REDIS_PORT=6379
            - SESSION_SECRET=secret
            - FRONTEND_DOMAIN=localhost:3000
            - NODE_ENV=${NODE_ENV:-development}
            - AWS_REGION=${AWS_REGION}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        # Wait until the database is running before starting the API
        command: ["wait-for-it", "-h", "hash-dev-pg", "-p", "5432", "-s", "-t", "30", "--", "./start.sh"]
        volumes:
            - ../backend/src:/app/packages/hash/backend/src
            - ../shared/src:/app/packages/hash/shared/src
            - ../backend-utils:/app/packages/hash/backend-utils
        stop_signal: SIGINT
    hash-dev-realtime:
        build:
            context: ../../../
            dockerfile: packages/hash/docker/realtime/dev/Dockerfile
        depends_on:
            - hash-dev-pg
            - hash-dev-redis
        ports:
            - 3333:3333
        environment:
            - HASH_PG_HOST=hash-dev-pg
            - HASH_PG_USER=postgres
            - HASH_PG_PORT=5432
            - HASH_PG_DATABASE=postgres
            - HASH_PG_PASSWORD=postgres
            - HASH_REALTIME_PORT=3333
            - HASH_REDIS_HOST=hash-dev-redis
            - HASH_REDIS_PORT=6379
        volumes:
          - ../realtime:/app/packages/hash/realtime
          - ../backend-utils:/app/packages/hash/backend-utils
volumes:
    # Make sure you have created this volume: docker volume create hash-dev-pg
    hash-dev-pg:
        external: true
