[package]
name = "server"
version = "0.0.0"
edition = "2018"

[dependencies]
hash_engine = { path = "../.." }

log = "0.4.11"
tokio = { version = "1.5.0", features = ["macros", "rt-multi-thread", "sync", "process", "io-util", "net", "rt", "fs"] }
