name: "Linter"
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - run: yarn install

      - run: yarn lint:workspaces
        if: ${{ success() || failure() }}

      - run: yarn lint:markdownlint
        if: ${{ success() || failure() }}

      - run: yarn lint:prettier
        if: ${{ success() || failure() }}
